# Generated by Django 5.0.3 on 2024-07-03 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending_payment", "منتظر پرداخت"),
                    ("registering_pos", "درحال ثبت کارتخوان"),
                    ("shipped", "ارسال شده"),
                    ("delivered", "تحویل داده شده"),
                ],
                default="pending_payment",
                max_length=20,
            ),
        ),
    ]
