# Generated by Django 5.0.3 on 2024-06-23 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Coupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=5, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("discount", models.FloatField()),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Faq",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.TextField()),
                ("answer", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Services",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="media/")),
                ("title", models.CharField(max_length=200)),
                ("text", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("message", models.TextField()),
                ("date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(allow_unicode=True, blank=True, unique=True)),
                ("price", models.PositiveIntegerField()),
                ("image", models.ImageField(upload_to="media/")),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("device_status", models.CharField(max_length=50, null=True)),
                (
                    "color",
                    models.CharField(
                        choices=[
                            ("red", "Red"),
                            ("blue", "Blue"),
                            ("green", "Green"),
                            ("black", "Black"),
                            ("yellow", "Yellow"),
                            ("white", "White"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("is_used", models.BooleanField(default=False)),
                ("charging_time", models.CharField(max_length=50, null=True)),
                ("charge_duration", models.CharField(max_length=50, null=True)),
                ("battery_capacity", models.CharField(max_length=50, null=True)),
                ("transaction_speed", models.CharField(max_length=20, null=True)),
                ("ram_memory", models.CharField(max_length=20, null=True)),
                ("display_type", models.CharField(max_length=20, null=True)),
                ("display_color", models.CharField(max_length=20, null=True)),
                ("display_size", models.CharField(max_length=20, null=True)),
                ("printer_type", models.CharField(max_length=50, null=True)),
                ("keyboard_type", models.CharField(max_length=20, null=True)),
                ("weight", models.CharField(max_length=20, null=True)),
                ("dimensions", models.CharField(max_length=50, null=True)),
                ("bluetooth", models.BooleanField(null=True, verbose_name="بلوتوث")),
                ("gprs", models.BooleanField(null=True, verbose_name="GPRS")),
                ("wifi", models.BooleanField(null=True, verbose_name="WiFi")),
                ("connected_banks", models.CharField(max_length=100, null=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.category"
                    ),
                ),
            ],
            options={
                "ordering": ["-created"],
            },
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("review", models.TextField()),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("active", models.BooleanField(default=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="main.product",
                    ),
                ),
            ],
            options={
                "ordering": ["-created"],
                "indexes": [
                    models.Index(
                        fields=["created"], name="main_commen_created_7f3688_idx"
                    )
                ],
            },
        ),
    ]
