# Generated by Django 5.0.3 on 2024-03-25 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(allow_unicode=True, blank=True, unique=True)),
                ("price", models.PositiveIntegerField()),
                ("image", models.ImageField(upload_to="media/")),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now_add=True)),
                ("description", models.TextField()),
                ("stock", models.PositiveIntegerField()),
                (
                    "color",
                    models.CharField(
                        choices=[("red", "Red"), ("blue", "Blue"), ("green", "Green")],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("count", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["-created"],
            },
        ),
    ]
