# Generated by Django 5.0.3 on 2024-04-15 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_category_product_category_comment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="count",
        ),
        migrations.RemoveField(
            model_name="product",
            name="description",
        ),
        migrations.RemoveField(
            model_name="product",
            name="stock",
        ),
        migrations.AddField(
            model_name="product",
            name="battery_capacity",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="bluetooth",
            field=models.BooleanField(null=True, verbose_name="بلوتوث"),
        ),
        migrations.AddField(
            model_name="product",
            name="charge_duration",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="charging_time",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="connected_banks",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="dimensions",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="display_color",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="display_size",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="display_type",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="gprs",
            field=models.BooleanField(null=True, verbose_name="GPRS"),
        ),
        migrations.AddField(
            model_name="product",
            name="is_used",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="product",
            name="keyboard_type",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="printer_type",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="ram_memory",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="transaction_speed",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="weight",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="wifi",
            field=models.BooleanField(null=True, verbose_name="WiFi"),
        ),
        migrations.AlterField(
            model_name="product",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
