# Generated by Django 5.0.3 on 2024-04-15 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_remove_product_count_remove_product_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="device_status",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="color",
            field=models.CharField(
                choices=[
                    ("red", "Red"),
                    ("blue", "Blue"),
                    ("green", "Green"),
                    ("black", "Black"),
                    ("yellow", "Yellow"),
                    ("white", "White"),
                ],
                max_length=10,
                null=True,
            ),
        ),
    ]
