# Generated by Django 5.0.3 on 2024-04-15 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_product_device_status_alter_product_color"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
