# Generated by Django 5.0.3 on 2024-04-24 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0008_alter_comment_updated"),
    ]

    operations = [
        migrations.AlterField(
            model_name="services",
            name="image",
            field=models.ImageField(upload_to="media/"),
        ),
    ]
